//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agri_Energy_Connect_Web_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> FarmerID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    
        public virtual Farmer Farmer { get; set; }
    }
}
